### ISSUE TITLE
Option 'renderType' needs to be specified for FlexForm type 'select'

### ISSUE THREAD

**Issue by nico-herbig** [frohland/ezqueries#3]
Since TYPO3 CMS 7.6 each `select` type in TCA and FlexForm need to be precised by a second configuration option called `renderType`. In TYPO3 CMS the following options are available:

- **`selectMultipleSideBySide`** - Two select fields, items can be selected from the right field, selected items are displayed in the left select.
- **`selectCheckBox`** - List of checkboxes for selecting muliple values.
- **`selectSingle`** - Normal select field for selecting a single value.
- **`selectSingleBox`** - Normal select field for selecting multiple values.
- **`selectTree`** - A tree for selecting hierarchical data.

For to 1 associations we should use **`selectSingle`** and for to n associations **`selectMultipleSideBySide`**, which is also the default behavior in TYPO3 CMS 6.2.

**Note:** Currently it seems that there is a display bug when using **`selectMultipleSideBySide`** in combination with **`<itemsProcFunc>`**, because after storing a plugin configuration the selected items on the left are correctly stored inside the database but not shown anymore. Therefore we need to switch to **`selectSingleBox`** and use `ctrl` key for multiple selection.

@frohland Could you live with that change? If so I would like to commit the changes.

**Comment by frohland** [comment]
@nico-herbig I would prefer renderType "selectCheckBox".

**Comment by nico-herbig** [comment]
I need to investigate this further because it is currently only a problem for the `table` setting in FlexForm. For all other settings it seems to be working. I will do this tomorrow.

**Comment by frohland** [comment]
No further investigation needed. I´ve found the solution 👍 .

**Comment by frohland** [comment]
Solution: In FlexFormUtility.php is a function called `showDatabaseTables`. In this function the line `$optionList[] = array(0 => '', 1 => 0);` needs to be commented out.

**Comment by nico-herbig** [comment]
Ok, this solution is working for me, too. 
Is it ok, if I remove the above code from `FlexFormUtility.php` completely?

**Comment by frohland** [comment]
Yes, you can remove it.
