### ISSUE TITLE
Adapt `<script>browse_link.php</script>` wizard registration

### ISSUE THREAD

**Issue by nico-herbig** [frohland/ezqueries#4]
The way registering a wizard in TCA and FlexForm has changed in TYPO3 CMS 6.2 and was removed in TYPO3 CMS 7. 

For FlexForm the code:

```
<script>browse_links.php?mode=wizard&act=file</script>
```

must be replaced by:

```
<module type="array">
  <name>wizard_element_browser</name>
    <urlParameters type="array">
      <mode>wizard</mode>
      <act>file</act>
  </urlParameters>
</module>
```

Detailed information could be found at https://wiki.typo3.org/Exception/CMS/1437750231.

**Comment by frohland** [comment]
@nico-herbig I already changed this.
